[Variables]
NumberOfMines=40
NumberOfRows=16
NumberOfCols=16
Questions=0

SquareSize=21
SquareMargin=4

InputX=286
InputY1=240
InputY2=276
InputY3=312

BeginnerTime1=16
BeginnerDate1=20:08 PM on 24 Jun 2012
BeginnerTime2=28
BeginnerDate2=11:08 AM on 19 Nov 2011
BeginnerTime3=64
BeginnerDate3=16:41 PM on 26 Nov 2011
BeginnerTime4=999
BeginnerDate4=Never
BeginnerTime5=999
BeginnerDate5=Never
BeginnerPlayed=7
BeginnerWon=3
BeginnerStreak=1
BeginnerMostWins=2
BeginnerMostLosses=3

IntermediateTime1=115
IntermediateDate1=14:53 PM on 26 Jun 2012
IntermediateTime2=999
IntermediateDate2=Never
IntermediateTime3=999
IntermediateDate3=Never
IntermediateTime4=999
IntermediateDate4=Never
IntermediateTime5=999
IntermediateDate5=Never
IntermediatePlayed=8
IntermediateWon=1
IntermediateStreak=-1
IntermediateMostWins=1
IntermediateMostLosses=6

AdvancedTime1=999
AdvancedDate1=Never
AdvancedTime2=999
AdvancedDate2=Never
AdvancedTime3=999
AdvancedDate3=Never
AdvancedTime4=999
AdvancedDate4=Never
AdvancedTime5=999
AdvancedDate5=Never
AdvancedPlayed=0
AdvancedWon=0
AdvancedStreak=0
AdvancedMostWins=0
AdvancedMostLosses=0
